version: '3'
services:
  api:
    build: '.'
    ports:
    - "8080:8080"
  frontend:
    build: './frontend'
    ports:
    - "3000:3000"
    depends_on:
    - api
    restart: on-failure
  backend:
    build: "./backend"
    ports:
    - "5050:5050"
    depends_on:
    - api
    #restart: on-failure
